name: Test
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Environment..
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: |
          bash bot.sh
          msg() {
            echo -e "\e[1;32m$*\e[0m"
          }
          my_dir="$(pwd)"
          cd $my_dir
          rm -rf arcana.sh
          wget https://raw.githubusercontent.com/NFS86/Rom-Builder/master/arcana.sh
          echo ===========================================
          msg             Environment.
          echo ===========================================
          printenv
          echo ===========================================
          echo
          echo
          echo
          echo ===========================================
          msg             Linux versions.
          echo ===========================================
          cat /etc/os*
          echo ===========================================
          echo
          echo
          echo
          echo ===========================================
          msg            Check user active.
          echo ===========================================
          w
          echo ===========================================
          echo
          echo
          echo
          echo ===========================================
          msg               Disk available.
          echo ===========================================
          lsblk && df -h
          echo ===========================================
          curl -s -X POST "https://api.telegram.org/bot${tg_token}/sendMessage" -d chat_id="${tg_id}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="<code>Hello.</code>"
