name: Test
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

env:
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_ID: ${{ secrets.TG_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Environment..
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        command: |
          export tg_token=$TG_TOKEN
          export tg_id=$TG_ID
          msg() {
            echo -e "\e[1;32m$*\e[0m"
          }
          my_dir="$(pwd)"
          cd $my_dir
          rm -rf arcana.sh
          wget https://raw.githubusercontent.com/NFS86/Rom-Builder/master/arcana.sh
          echo ===========================================
          msg             Linux versions.
          echo ===========================================
          printenv
          echo ===========================================
          
          
          
          echo ===========================================
          msg             Linux versions.
          echo ===========================================
          cat /etc/os*
          echo ===========================================
          
          
          
          echo ===========================================
          msg            Check user active.
          echo ===========================================
          w
          echo ===========================================
          
          
          
          echo ===========================================
          msg               Disk available.
          echo ===========================================
          lsblk && df -h
          echo ===========================================
